### ISSUE TITLE
Error can’t start F1 TV Pro

### ISSUE THREAD

**Issue by ssmith1936** [bbsan2k/plugin.video.f1tv#17]
I’m getting Error can’t start F1 TV on Kodi 18.5 RPi3 and Nvidia shield latest software ( android). The plugin starts and I can navigate to a desired video, but can’t launch a live session nor the archived races. Really love this plugin and hope it can be fixed. The ROKU F1 app is underperforming so far.

**Comment by TheDevFreak** [comment]
This is known, see #14 

I have also just merged changes to fix to master so you are welcome to download new addon zip.

**Comment by ssmith1936** [comment]
Where do I get the new addon zip?

**Comment by TheDevFreak** [comment]
This file: https://github.com/bbsan2k/plugin.video.f1tv/archive/master.zip will always net you the most up to date file.

@bbsan2k Can I have collaborator on https://github.com/bbsan2k/repository.f1tv/ too?

**Comment by bbsan2k** [comment]
@TheDevFreak for sure😊 there you go!

**Comment by ssmith1936** [comment]
Thanks!

Sincerely,
Sylvester Smith, Jr.
Engineering Manager, Corporate Standards lab
Eli Lilly and Company
Office: 317-276-0497
Mobile: 317-292-0362 
Email: smith_sylvester_jr@lilly.com | Web: http://www.lilly.com
