### ISSUE TITLE
Can’t launch the Kodi F1 plugin on multiple platforms 

### ISSUE THREAD

**Issue by ssmith1936** [bbsan2k/plugin.video.f1tv#20]
I use the kodi plugin on a Kodi 18.5 RBPi3 and, after resetting password, can no longer even login. Also can’t launch live or archived streams on kodi plugin on Nvidia shield. The RBPi3 has a VPN and the Nvidia shield doesn’t. Can’t launch live or archived video on either.  I Love this plugin, hope you continue to support it.

**Comment by ragnos** [comment]
This has been fixed by PR #18 . Just download and install the zip-file again, and you're good to go. Archived video still seems to be an issue due to API changes, but TheDevFreak is on it.

**Comment by bjorn1981** [comment]
Archived video and sets are also fixed with 0.1.0

**Comment by TheDevFreak** [comment]
Fixed with 0.1.0 - if your issue persists let me know.

**Comment by ssmith1936** [comment]
Thanks!
