### ISSUE TITLE
Account Authentication Failed

### ISSUE THREAD

**Issue by iblagoev** [bbsan2k/plugin.video.f1tv#24]
I'm trying to run the plugin (version 1.0) on RPi 3B+ running Debian Stretch with Kodi 18.2. I have provided my login credentials in the plugin settings, but whenever I start it I get "Authentication Failed". 
My subscription is F1 TV Pro. 

Here is the error from the log:

> ERROR: Account Authentification failed.
> INFO: CPythonInvoker(16, /root/.kodi/addons/plugin.video.f1tv/main.py): script aborted
DEBUG: onExecutionDone(16, /root/.kodi/addons/plugin.video.f1tv/main.py)
INFO: Python interpreter stopped
DEBUG: Thread LanguageInvoker 1549791968 terminating
ERROR: GetDirectory - Error getting plugin://plugin.video.f1tv/
Thread waiting 1541399264 terminating
DEBUG: ------ Window Deinit (DialogBusy.xml) ------
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/) failed
DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/video)

**Comment by TheDevFreak** [comment]
Try resetting your password on the account.formula1.com website

**Comment by iblagoev** [comment]
That worked.
