### ISSUE TITLE
Account Authenticator failing on RPI

### ISSUE THREAD

**Issue by ssmith1936** [bbsan2k/plugin.video.f1tv#26]
on RPI3b. I get the old ‘Account Authentication failed’ message with VPN on. I get to the legend screen which lists options for viewing by Season,Circuit, etc. But can go no further. Have logged out, back in, nothing.  VPN worked before. With VPN off, login works.

**Comment by TheDevFreak** [comment]
> With VPN off, login works.

You need to turn your VPN off go to account.formula1.com and change your password (you can just change it to be the same as it currently is) then try again with VPN on in kodi.

**Comment by ssmith1936** [comment]
Thanks, I’ll try this. 🙂

**Comment by bbsan2k** [comment]
I guess this is resolved now..
