### ISSUE TITLE
shows section not listed

### ISSUE THREAD

**Issue by steph09** [bbsan2k/plugin.video.f1tv#3]
Just wondering if it would be possible to add the 'shows' section that includes some documentaries and other programming?

All the seasons and races that are on the service are listed and playing perfectly but the shows section of the service is missing from the addon.

**Comment by bbsan2k** [comment]
Yes, this should be possible- I‘ll try to look into that this weekend!
Good idea!

**Comment by bbsan2k** [comment]
Just it give you some heads up:
I started working on this, but ran into some login issues😉 I‘ll Update this issue once it is integrated

**Comment by Mimomaj** [comment]
Do you have any update on this please?

**Comment by TheDevFreak** [comment]
This is implemented under the 'sets' section (although this is currently broken due to #16 needing to be fixed)
