### ISSUE TITLE
can´t run Kodi-Plugin after fresh install and can´t access any streams

### ISSUE THREAD

**Issue by nyhtz** [bbsan2k/plugin.video.f1tv#34]
Hello, i have 2 Firetv-Sticks, with both kodi and the plugin installed.

On the first one I installed the plugin, but i can´t run the plugin. Also the picture of the plugin is not an f1-logo(which should be or?). I can´t do anything with the addon. On my other device the addon set up everything automaticly, I just needed to login. I did a fresh installation of kodi and the plugin 3 times now. 

On the second One, the plugin and kodi worked until yesterday or so. I can access the plugin and choose the race-options etc. But I can´t start a stream. If I click on a selection the plugin starts loading and ends loadion about 30 seconds later with doing nothing. I tried it with live and archive races, none is loading.

Hope you stay safe and healthy

**Comment by phochrist** [comment]
Hi,
I have also issues with the last changes. It works for me after going back to an earlier version:
git reset --hard e4968b79968645a6e23a7624494078af45abfb8c

Best
phochrist

**Comment by bbsan2k** [comment]
Hey,

This MIGHT be related to the python on a firetv...
Also - can you please add your region? Sometimes we saw issues in some regions whereas in other everything worked fine...

**Comment by bbsan2k** [comment]
Reverted to 0.1.3 for now. Please uninstall and reinstall the plugin from repository...
