### ISSUE TITLE
Does not authenticate sign-in credentials within Kodi 17.6 for Android TV

### ISSUE THREAD

**Issue by ssmith1936** [bbsan2k/plugin.video.f1tv#4]
Installed this app on 2 devices:  a.) RBPi3B and b.) Nvidia Shield with latest Android TV.   Works great on my Raspberi Pi 3B on KODI 17.6 w/ Libreelec.     I loaded your release 5 zip file from github via a usb drive.   It did take several clicks to get the race video links to start playing video. I got the 'item failed to play' message 1-2 times before it would play.  But it did play and played, FF, RW etc. well....works fine on the RBPi3B.

I then loaded the same F1TV release 5 zip onto my Nvidia Shield with Android TV running a KODI 17.6 build. The app loaded after a couple of attempts.  I then entered my login info and started the addon.  I got to the menu within the addon , and I browsed to and selected a race to play, but got an error message that indicated that my logon was not authenticated and I needed to go to settings to check/reenter my credentials. This started a loop where I was forced to either reenter my logon Id and password or hit ok and  get the same 'logon credentials not authenticated' error.  Hitting escape would kick me out of the addon within kodi.  I could not play a video on the Android TV device. Running Kodi 17.6 on Shield Android TV SW Version 7.2.2 (30.7.130.7).

Hope this helps in your troubleshooting.  I like using it on my RBPi so far.

**Comment by bbsan2k** [comment]
Hi!
I also started working on this, it looks like f1tv is now checking more header attributes than before. I had some troubles logging in this weekend, so I didn‘t come very far.
Hopefully I can get this done this week!

**Comment by cmsimike** [comment]
I was able to log in it seems without a problem, but when I went to view the practices, none of the videos load anymore.

**Comment by cmsimike** [comment]
I am not unable to log in completely while my login works on the website. It was working when I posted, as I got to the point of trying to watch the first practice, but the video wouldn't load. Then it would not let me login anymore.

**Comment by steph09** [comment]
Seems like maybe something the addon does causes F1TV to block your IP somehow as i've noticed that when I get the login error with the addon I also start getting 'Invalid credentials' errors when trying to login to the website & the only thing that fixes it is disconnecting my internet connection which changes my IP address (My ISP uses a dynamic IP), Using a VPN or something also works.

It will work fine after this until I use the addon to watch 2-3 things & then it will happen again until I login with a different IP address...  Rince & repeat.

Maybe they have incorporated something that detects your not using there website or official apps or something?

**Comment by cmsimike** [comment]
@steph09 For what it's worth, I have a static IP (so it doesn't change) and I've had no problems logging into the website but still have issues with the plugin.

I hope there is a work around for this as watching f1 through kodi is just fantastic for me.

**Comment by bbsan2k** [comment]
I think so too.
I also checked this and it seems even at first attempt the login fails.
Currently, the addon only uses a minimal set of request headers.
It‘s really hard to debug, as each time an attempt fails more than one time I need to wait until my account is unsuspended again...

**Comment by vaiosp** [comment]
I was able to login with no issues today. I use Kodi for Android on a TVBox with Superceleron's firmware (not the Android TV version) I will try to watch a few things my self to find out if it gets me blocked as well. Oh, bbsan, Thank you. Not the f1tv app , nor Firefox or Chrome for Android manages to show the best quality available. This plugin does. It has the exact same quality on my TV when watching through the browser on my laptop connected through HDMI.

**Comment by vaiosp** [comment]
Yeap. After 3 videos I got a username error.

**Comment by ssmith1936** [comment]
Upgraded to Kodi 18.1 on  Nvidia Shield w/ Android TV latest firmware, and now I can login to F1TV and watch video fine. I had to turn off my VPN however.  With VPN on, I got the login errors first mentioned with Kodi 17.6. But, I didn’t check to see what happens if I attempted to watch multiple videos during a Login session. Will check later.

**Comment by ssmith1936** [comment]
On a separate note, upgraded to Kodi 18.0 on a RaspberryPi with Libreelec 9.0, I can login to F1TV and watch video with my VPN on. Fewer issues all around on the RPI.

**Comment by vaiosp** [comment]
I am also using Kodi 18.1 downloaded from the play store and the only extra plugin installed is Plex. I am not using VPN as I am in Greece and we got F1TV pro officially supported. I haven't tried rebooting my router yet to see if it instantly lets me login again) but will do so tomorrow that I will have more time...

**Comment by TheDevFreak** [comment]
This issue does not exist on my Android TV credentials currently. 

Submit new issue / ask for this to be reopened if issue persists.
