### ISSUE TITLE
Install problem in kodi 18.9

### ISSUE THREAD

**Issue by hblek** [bbsan2k/plugin.video.f1tv#45]
I had a problem with kodi 19, I remover kodi from my mibox3 and installed kodi 18.9
Adding the f1tv addon showed a correct. Instalation popup, but addon does. Not appear on the video addons. Wiping kodi and reinstalling again does not solve the issue.
I hope you can help me to solve the issue.
The mibox3 was recently updated to androidtv 9
Kind regards, hblek

**Comment by hblek** [comment]
At least the plugin was installed. However addon returned loading error. Updated to matrix, ap can be installed but  an not be e a led incompatible error for matrix.
How to proceed?

**Comment by bbsan2k** [comment]
Please see https://github.com/bbsan2k/plugin.video.f1tv/issues/44#issuecomment-830780572
