### ISSUE TITLE
Lagg

### ISSUE THREAD

**Issue by felipecorrea9** [bbsan2k/plugin.video.f1tv#5]
Hi,
I tested version 0.0.5, and it works, but Im getting a lot of lagg. The video stops loading some times. Im using a Raspberry Pi model 3 wired, not wifi with Kodi 17.5.

The stream works fine on my laptop using the F1.com website. Any idea if it is a config issue?

Regards

**Comment by bbsan2k** [comment]
Hey,
This may be related to the fact that the plugin always tries to get the best quality stream. What kind of internet connection do you have?
If you are using KODI 17 you can try to switch the "channel" and choose one with less quality (like 1080P).

Also, please try if the stream works in KODI on PC - if so it could also be 4K decoding issues on Raspberry Pi 3

**Comment by felipecorrea9** [comment]
I have a 400 Mb internet connection Its really fast.

I installed Kodi 18 and tweak the cache a bit. It got better, but it still laggs some times. 
Today I will try to watch live content, yesterday Inwas only watching replays.

**Comment by bbsan2k** [comment]
You may give some feedback about this, but AFAIK Live doesn't work good because of the way F1TV delivers the m3u8 streams.
If it works please give me a small update 😉 Thx!

**Comment by felipecorrea9** [comment]
I just test the replays on Kodi on my computer (windows 10). Same behavour.  It laggs. No problem using Chrome.

**Comment by TheDevFreak** [comment]
Issue is not reproducible on my end

Submit new / ask for reopen if issue persists.
