### ISSUE TITLE
App stopped working on Kodi. 0.1.7

### ISSUE THREAD

**Issue by rawmeat83** [bbsan2k/plugin.video.f1tv#50]
Good Afternoon,
When going to current event the sessions don't show up anymore. I tried updating on Kodi the app but it didn't work. Appreciate any help.

**Comment by antoinelochet** [comment]
I had the same issue but then then I saw that a beta was released for Kodi Matrix so I updated and it worked nicely.
If you can do the same, I can only advise you to do just than.

**Comment by rawmeat83** [comment]
> I had the same issue but then then I saw that a beta was released for Kodi Matrix so I updated and it worked nicely.
> If you can do the same, I can only advise you to do just than.

Only issue is I'm trying to run it on Xbox and Kodi Matrix beauty is not available on Xbox marketplace.

**Comment by archulet** [comment]
App stopped showing ONGOING SESSIONS on Libreelec running Kodi Leia, only recorded programs showing, please advice bbsan2k ...

**Comment by archulet** [comment]
Or DevFreak ...

**Comment by bbsan2k** [comment]
@archulet For now, the addon will only target Matrix because of some dependencies. Please use latest LE beta if you want to keep using the addon…

**Comment by rawmeat83** [comment]
@bbsan2k  using kodi Matrix when i enter that path url it won't pull up the repository, its just blank ...    Any word on Matrix kodi for xbox?

**Comment by archulet** [comment]
Thanks @bbsan2k , I'll migrate to newer version, best regards!

**Comment by archulet** [comment]
@bbsan2k same for me on RPi4 with LibreElec Matrix Beta not showing the zip on the URL trough File manager/Source, not even installing directly from the .zip archive manually works, it reports as installed but no appearance on Add-ons tag ...

**Comment by archulet** [comment]
@bbsan2k, checking the different file access within the app, it seems that only the last Portugal Grand Prix is affected, thanks in advance for your efforts (Platform and OS = RPi3, RPi4, LE, Leia).

**Comment by archulet** [comment]
@bbsan2k, on another RPi4 with LE-Matrix the add-on installation is not working.

**Comment by Spacefreak18** [comment]
I upgraded to Matrix, I tried the new plugin, I even tried the latest from the Matrix_New_Api branch and I still seem to have issues. The apps shows Archives, Documentaries, etc, but nothing else works. I'd expect it to show a current event for the Spanish Grand Prix. 

Is there something I'm doing wrong, I'll try to help anyway I can.

**Comment by Spacefreak18** [comment]
I went ahead and deleted my .kodi folder. Reinstalled the plugin from here: https://github.com/bbsan2k/plugin.video.f1tv/releases/tag/0.1.100 and it seems to be working.

**Comment by bbsan2k** [comment]
If you want to use auto update and repository install, please use [This](https://github.com/bbsan2k/repository.f1tv/raw/Matrix/zips/repository.f1tv/repository.f1tv-2.0.zip) for Matrix
