### ISSUE TITLE
RPi4 - Audio/Video out of sync

### ISSUE THREAD

**Issue by mcapinha** [bbsan2k/plugin.video.f1tv#52]
I'm using a RPi4, coming from my previous Kodi install on a RPi3.
I tried installed the plugin on fresh installs of OSMC beta and LE beta, both running Kodi Matrix.

On both installs, when I play any video from the Spain GP, there's a very considerable lag between video and audio (3 or 4 seconds, at least). This can be observed on the Pre-Race show, when we the commentator shows up.

I've done some digging and there are some reports of problems when the interface resolution is different from the video. I've set the interface to 1920x1080p but the problem remains.

Other videos (non-streaming) play just fine.
I've got limited experience with Kodi on the RPi4 and am not 100% sure if this is plugin related or not.

**Comment by bbsan2k** [comment]
This is probably kodi related as the plug-in uses the Video play facilities of kodi. Also it is working on other platforms which makes me believe it could be related to the hardware decoder interface on the raspberry pi 4:(

**Comment by joostpielage** [comment]
@mcapinha did you ever manage to fix this? I have the exact same issue.

**Comment by mcapinha** [comment]
Yup. IIRC I set the refresh rate to 60Hz and it is working now. Let me know
if this doesn't work and I'll have a look at the exact setting.

**Comment by joostpielage** [comment]
Yeah please check for me. Where did you change the refresh rate? In the
Kodi settings or on your OS level?

**Comment by mcapinha** [comment]
I only changed the settings in Kodi.

So, go into Settings / System / Display and set the resolution to
1920x1080p and Refresh Rate to 60HZ.
IIRC the problem was the UI resolution and refresh rate being different
from the feed source.
