### ISSUE TITLE
Streams not starting on kodi 18.4 on Amazon Firestick

### ISSUE THREAD

**Issue by bertiebassett** [bbsan2k/plugin.video.f1tv#9]
I love this add-on, and it works beautifully on my Windows HTPC. However, I also installed it on my Firestick and I can’t get a stream to start to play. It loads for a bit, then displays the play symbol in the top right, loads for a bit longer then... nothing happens. Just back to the list of race or driver names. 

Pretty much a vanilla install of Kodi 18.4. Are there any other addons I need to install to get the streams to work? Or any settings to alter?

InputStreamAdaptive is installed, and other streaming addons work ok.

**Comment by TheDevFreak** [comment]
Closing due to old/inactivity if this issue still exists please start a new issue or comment on this one too be reopened.
